/* tslint:disable */
/* eslint-disable */
/**
 * auto generated spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ApiJobJobDELETEResponse200
 */
export interface ApiJobJobDELETEResponse200 {
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobDELETEResponse200
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface ApiJobJobGETResponse200
 */
export interface ApiJobJobGETResponse200 {
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobGETResponse200
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobGETResponse200
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobGETResponse200
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobGETResponse200
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobGETResponse200
     */
    'user_id': number;
}
/**
 * 
 * @export
 * @interface ApiJobJobPUTRequest
 */
export interface ApiJobJobPUTRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobPUTRequest
     */
    'user_id': number;
}
/**
 * 
 * @export
 * @interface ApiJobJobPUTResponse200
 */
export interface ApiJobJobPUTResponse200 {
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobPUTResponse200
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse200
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse200
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse200
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobPUTResponse200
     */
    'user_id': number;
}
/**
 * 
 * @export
 * @interface ApiJobJobPUTResponse403
 */
export interface ApiJobJobPUTResponse403 {
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse403
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse403
     */
    'exception': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse403
     */
    'file': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobJobPUTResponse403
     */
    'line': number;
    /**
     * 
     * @type {Array<ApiJobPOSTResponse403Trace>}
     * @memberof ApiJobJobPUTResponse403
     */
    'trace': Array<ApiJobPOSTResponse403Trace>;
}
/**
 * 
 * @export
 * @interface ApiJobJobPUTResponse422
 */
export interface ApiJobJobPUTResponse422 {
    /**
     * 
     * @type {string}
     * @memberof ApiJobJobPUTResponse422
     */
    'message': string;
    /**
     * 
     * @type {ApiJobPOSTResponse422Errors}
     * @memberof ApiJobJobPUTResponse422
     */
    'errors': ApiJobPOSTResponse422Errors;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTRequest
 */
export interface ApiJobPOSTRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobPOSTRequest
     */
    'user_id': number;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTResponse200
 */
export interface ApiJobPOSTResponse200 {
    /**
     * 
     * @type {number}
     * @memberof ApiJobPOSTResponse200
     */
    'user_id': number;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse200
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTResponse403
 */
export interface ApiJobPOSTResponse403 {
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403
     */
    'exception': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403
     */
    'file': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobPOSTResponse403
     */
    'line': number;
    /**
     * 
     * @type {Array<ApiJobPOSTResponse403Trace>}
     * @memberof ApiJobPOSTResponse403
     */
    'trace': Array<ApiJobPOSTResponse403Trace>;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTResponse403Trace
 */
export interface ApiJobPOSTResponse403Trace {
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403Trace
     */
    'file': string;
    /**
     * 
     * @type {number}
     * @memberof ApiJobPOSTResponse403Trace
     */
    'line': number;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403Trace
     */
    'function': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403Trace
     */
    'class': string;
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse403Trace
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTResponse422
 */
export interface ApiJobPOSTResponse422 {
    /**
     * 
     * @type {string}
     * @memberof ApiJobPOSTResponse422
     */
    'message': string;
    /**
     * 
     * @type {ApiJobPOSTResponse422Errors}
     * @memberof ApiJobPOSTResponse422
     */
    'errors': ApiJobPOSTResponse422Errors;
}
/**
 * 
 * @export
 * @interface ApiJobPOSTResponse422Errors
 */
export interface ApiJobPOSTResponse422Errors {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiJobPOSTResponse422Errors
     */
    'name': Array<string>;
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    'user_id': number;
}
/**
 * 
 * @export
 * @interface InlineResponse500
 */
export interface InlineResponse500 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500
     */
    'exception': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500
     */
    'file': string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse500
     */
    'line': number;
    /**
     * 
     * @type {Array<InlineResponse500Trace>}
     * @memberof InlineResponse500
     */
    'trace': Array<InlineResponse500Trace>;
}
/**
 * 
 * @export
 * @interface InlineResponse500Trace
 */
export interface InlineResponse500Trace {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500Trace
     */
    'file': string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse500Trace
     */
    'line': number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500Trace
     */
    'function': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500Trace
     */
    'class': string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500Trace
     */
    'type': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobGET: async (contentType?: string, accept?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/job`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (accept !== undefined && accept !== null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 57
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobDELETE: async (job: number, contentType?: string, accept?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'job' is not null or undefined
            assertParamExists('apiJobJobDELETE', 'job', job)
            const localVarPath = `/api/job/{job}`
                .replace(`{${"job"}}`, encodeURIComponent(String(job)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (accept !== undefined && accept !== null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 56
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobGET: async (job: number, contentType?: string, accept?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'job' is not null or undefined
            assertParamExists('apiJobJobGET', 'job', job)
            const localVarPath = `/api/job/{job}`
                .replace(`{${"job"}}`, encodeURIComponent(String(job)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (accept !== undefined && accept !== null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 58
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobJobPUTRequest} [apiJobJobPUTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobPUT: async (job: number, contentType?: string, accept?: string, apiJobJobPUTRequest?: ApiJobJobPUTRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'job' is not null or undefined
            assertParamExists('apiJobJobPUT', 'job', job)
            const localVarPath = `/api/job/{job}`
                .replace(`{${"job"}}`, encodeURIComponent(String(job)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (accept !== undefined && accept !== null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiJobJobPUTRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobPOSTRequest} [apiJobPOSTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobPOST: async (contentType?: string, accept?: string, apiJobPOSTRequest?: ApiJobPOSTRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/job`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (accept !== undefined && accept !== null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiJobPOSTRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiJobGET(contentType?: string, accept?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InlineResponse200>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiJobGET(contentType, accept, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 57
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiJobJobDELETE(job: number, contentType?: string, accept?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiJobJobDELETEResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiJobJobDELETE(job, contentType, accept, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 56
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiJobJobGET(job: number, contentType?: string, accept?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiJobJobGETResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiJobJobGET(job, contentType, accept, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 58
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobJobPUTRequest} [apiJobJobPUTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiJobJobPUT(job: number, contentType?: string, accept?: string, apiJobJobPUTRequest?: ApiJobJobPUTRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiJobJobPUTResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiJobJobPUT(job, contentType, accept, apiJobJobPUTRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobPOSTRequest} [apiJobPOSTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiJobPOST(contentType?: string, accept?: string, apiJobPOSTRequest?: ApiJobPOSTRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiJobPOSTResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiJobPOST(contentType, accept, apiJobPOSTRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobGET(contentType?: string, accept?: string, options?: any): AxiosPromise<Array<InlineResponse200>> {
            return localVarFp.apiJobGET(contentType, accept, options).then((request) => request(axios, basePath));
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 57
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobDELETE(job: number, contentType?: string, accept?: string, options?: any): AxiosPromise<ApiJobJobDELETEResponse200> {
            return localVarFp.apiJobJobDELETE(job, contentType, accept, options).then((request) => request(axios, basePath));
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 56
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobGET(job: number, contentType?: string, accept?: string, options?: any): AxiosPromise<ApiJobJobGETResponse200> {
            return localVarFp.apiJobJobGET(job, contentType, accept, options).then((request) => request(axios, basePath));
        },
        /**
         * /api/job/{job}
         * @summary /api/job/{job}
         * @param {number} job 58
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobJobPUTRequest} [apiJobJobPUTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobJobPUT(job: number, contentType?: string, accept?: string, apiJobJobPUTRequest?: ApiJobJobPUTRequest, options?: any): AxiosPromise<ApiJobJobPUTResponse200> {
            return localVarFp.apiJobJobPUT(job, contentType, accept, apiJobJobPUTRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * /api/job
         * @summary /api/job
         * @param {string} [contentType] application/json
         * @param {string} [accept] application/json
         * @param {ApiJobPOSTRequest} [apiJobPOSTRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiJobPOST(contentType?: string, accept?: string, apiJobPOSTRequest?: ApiJobPOSTRequest, options?: any): AxiosPromise<ApiJobPOSTResponse200> {
            return localVarFp.apiJobPOST(contentType, accept, apiJobPOSTRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiJobGET operation in DefaultApi.
 * @export
 * @interface DefaultApiApiJobGETRequest
 */
export interface DefaultApiApiJobGETRequest {
    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobGET
     */
    readonly contentType?: string

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobGET
     */
    readonly accept?: string
}

/**
 * Request parameters for apiJobJobDELETE operation in DefaultApi.
 * @export
 * @interface DefaultApiApiJobJobDELETERequest
 */
export interface DefaultApiApiJobJobDELETERequest {
    /**
     * 57
     * @type {number}
     * @memberof DefaultApiApiJobJobDELETE
     */
    readonly job: number

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobDELETE
     */
    readonly contentType?: string

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobDELETE
     */
    readonly accept?: string
}

/**
 * Request parameters for apiJobJobGET operation in DefaultApi.
 * @export
 * @interface DefaultApiApiJobJobGETRequest
 */
export interface DefaultApiApiJobJobGETRequest {
    /**
     * 56
     * @type {number}
     * @memberof DefaultApiApiJobJobGET
     */
    readonly job: number

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobGET
     */
    readonly contentType?: string

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobGET
     */
    readonly accept?: string
}

/**
 * Request parameters for apiJobJobPUT operation in DefaultApi.
 * @export
 * @interface DefaultApiApiJobJobPUTRequest
 */
export interface DefaultApiApiJobJobPUTRequest {
    /**
     * 58
     * @type {number}
     * @memberof DefaultApiApiJobJobPUT
     */
    readonly job: number

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobPUT
     */
    readonly contentType?: string

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobJobPUT
     */
    readonly accept?: string

    /**
     * 
     * @type {ApiJobJobPUTRequest}
     * @memberof DefaultApiApiJobJobPUT
     */
    readonly apiJobJobPUTRequest?: ApiJobJobPUTRequest
}

/**
 * Request parameters for apiJobPOST operation in DefaultApi.
 * @export
 * @interface DefaultApiApiJobPOSTRequest
 */
export interface DefaultApiApiJobPOSTRequest {
    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobPOST
     */
    readonly contentType?: string

    /**
     * application/json
     * @type {string}
     * @memberof DefaultApiApiJobPOST
     */
    readonly accept?: string

    /**
     * 
     * @type {ApiJobPOSTRequest}
     * @memberof DefaultApiApiJobPOST
     */
    readonly apiJobPOSTRequest?: ApiJobPOSTRequest
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * /api/job
     * @summary /api/job
     * @param {DefaultApiApiJobGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiJobGET(requestParameters: DefaultApiApiJobGETRequest = {}, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiJobGET(requestParameters.contentType, requestParameters.accept, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * /api/job/{job}
     * @summary /api/job/{job}
     * @param {DefaultApiApiJobJobDELETERequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiJobJobDELETE(requestParameters: DefaultApiApiJobJobDELETERequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiJobJobDELETE(requestParameters.job, requestParameters.contentType, requestParameters.accept, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * /api/job/{job}
     * @summary /api/job/{job}
     * @param {DefaultApiApiJobJobGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiJobJobGET(requestParameters: DefaultApiApiJobJobGETRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiJobJobGET(requestParameters.job, requestParameters.contentType, requestParameters.accept, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * /api/job/{job}
     * @summary /api/job/{job}
     * @param {DefaultApiApiJobJobPUTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiJobJobPUT(requestParameters: DefaultApiApiJobJobPUTRequest, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiJobJobPUT(requestParameters.job, requestParameters.contentType, requestParameters.accept, requestParameters.apiJobJobPUTRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * /api/job
     * @summary /api/job
     * @param {DefaultApiApiJobPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiJobPOST(requestParameters: DefaultApiApiJobPOSTRequest = {}, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiJobPOST(requestParameters.contentType, requestParameters.accept, requestParameters.apiJobPOSTRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


